<en una plaza.nos dan cocaina.alguien arma un cigarrillo.pienso probar un poco.empieza el guille.no le da por la nariz.lo fuma.pega una aspirada fuertisima.otro loco se asombra.sigue el cigarrillo.me llega.intento aspirar.salen pastillas.se caen.las junto.paso el cigarro.le toca al guille de nuevo.con todo.queda con la cara de la amiga del lobo>
<sol perez.SOL PEREZ! queria ser mi novia Y YO ME HACIA EL DICIFIL!.afuera de casa.estaba ella.no se que haciamos ahi.se me acerca.me empieza a hablar.me pregunta directamente.si quiero andar con ella.yo le pregunto si no tiene novio.me dice que si.le digo que termine con el novio primero.>hasta en sueños soy virgo maximo.
<un salon.una fiesta.como un cumpleaños.salimos con jorge a un negocio.el quiere comprar una horma entera de queso.10999 pesos.no llegamos.compramos un pedazo de 1000.otra escena.estamos comiendo en el negocio.entra una mina parecida a lucha.mas alta y flaca.se sienta en una mesa.con otros.cajon estaba ahi.maquillada.con escote.era el cumpleaños de lucha.le estoy contando lo del queso a martin lopez jordan y a otro loco.cajon se va a una mesa sola con el seba cozzi.despues viene a saludarme a mi.se me pone muy cerca.virgueo.se va.los que estaban ahi me empiezan a agrandar.nos vamos al salon.cajon se me acerca de nuevo.me esta coqueteando.se va de nuevo.seguimos caminando en el cumpleaños.mucha gente.sectores.pilas y pilas de vinos en cajita en el suelo.unos pibes corriendo carreras por ahi en autitos como los chocadores.tumban los vinos.no pueden pasar.yo cagandome de risa les digo que no es la solucion.por otro lado unos viejitos corriendo carreras en moto.no herminio.no herminio.grito tambien riendome de lo rara que es la situacion.>
<tenia un hijo con la mica(como si la conociera).pensaba que todavia no estaba listo.la veia pasar.aparecian sentimientos nuevos.de amor>.no estoy enamorado de ella.pero quiero sentir el afecto.ahora lo relaciono con ella.como desprender la figura del sentimiento.como la vez que soñe con cajon.voy a tener que meterla al top.
<me llamaban para un trabajo.no me acuerdo que era.los dias siguientes.esperando que me llamen.me llaman pero de otro lado.plastica venado.se ve que hago unas pruebas.me dan la ropa.cada puesto era de un color.creo que me dan una sabana tambien.me acuerdo que estaba a la espera del otro trabajo.que ya casi era seguro.que hago.>
<arriba.viendo tinder en la computadora.sube una mina.la actriz.una gordita.me pregunta como se hacia algo en la aplicacion o pagina.parece que le gusto.esquivo como buen virgo.me agarra y me besa.regaladisima.me dice que se tiene que ir a bañar.le digo que despues vuelva.habia alguien mas arriba.una mina conocida pero no se quien.de mi edad era.me quedo pensando en el beso.>
<iba en el auto.pellegrini y españa.dos autos adelante.freno de golpe.una mina venia cruzando.se choca el auto.como si no lo hubiese visto.medio que se tira arriba.se choca varias veces.me voy a bajar para ver si esta bien.tengo puesto un casco.>
<ibamos en el auto.el pollo.el fer.la uniceja.yo.por unos campos de choclos gigantes.digo algo para mostrar mi asombro.medio que empiezan a burlarse tratando que no me de cuenta.despues le voy a responder a la uniceja sobre esto.algo sobre el agua de choclo.capaz que me ofrecio agua y le digo que ya tome.ahora vamos camino al cementerio y empiezan a burlarse de un virgo.yo me siento medio para atras.creo que era marroquin.que estaban en un boliche y el pollo queria que marroquin fuera con el a buscar minas y el otro le dijo que no.nos bajamos y seguimos caminando.por una cinta transportadora.va muy rapido.no se porque pero la uniceja dice que esta a favor de la pena de muerte.la agarro y amago con tirarla de la cinta.a la velocidad que ibamos moria seguro.llegamos al final.la mina ahora es una bebe.se va gateando y llorando.la levanto y la llevo para atras.se calma.>
<me despiertan.me suben al auto y me llevan de una conocida de la titi.para verle algo de la computadora.voy tomando el cafe en el auto.me explican a medias que es.la nona maneja.mama atras.me bajan a los apurones.me re caliento.tiro el cafe a la mierda.la campera tambien.voy.dos minas.una linda y una fea.les digo que me expliquen me pasa.me hablan pero de otra cosa.viene luis.vestido formalmente.se pone a joder.no deja que me sigan contando las minas.se cambia toda la escena.ahora hay muchos tipos.>
<con los pibes.nos habiamos juntado a comer.estabamos en una pieza.chica.esperando a que llegue la pata.el agus hablando con una mina.mas grande.baqueteada.regalada.era zuleika esnal.la cosa se pone picante.la mina empieza a bailar arriba de la mesita donde hablaban.se abre de piernas.se baja.dice algo importante pero no me acuerdo que.le empieza a chupar la verga al agus.rapidamente todos nos ponemos en espera.sigue uno por uno.el patriarcado lo hizo de nuevo.cuando me esta por tocar a mi me despierto.obviamente.>