#+TITLE: práctica N1
#+DATE:
#+OPTIONS: toc:nil
#+LATEX_HEADER: \usepackage{fullpage}
1. 
   a.
   + punto a punto
     * enlace permanente entre dos puntos finales
   + bus
     * cada nodo está conectado a un cable central
     * todas las transmisiones en la red se realizan por este cable central o "bus"
     * más barata de implementar pero más dificil de manejar
     * si falla el bus la red queda dividida en dos
   + estrella
     * cada nodo periférico se conecta a uno central llamado "switch" o "hub"
     * cliente-servidor
     * toda la comunicación pasa por el nodo central, que trabaja como repetidor
     * fácil de diseñar e implementar. simplicidad para agregar nodos
     * si falla el nodo central falla toda la red
     * *estrella extendida*: una estrella central y varias subredes con repetidores
     * *estrella distribuída*: varias subredes estrella conectadas cada una con la siguiente (daisy-chain)
   + anillo
     * daisy-chain formando un bucle
     * los datos viajan sólo en una dirección
     * el rendimiento es mejor que el de la topología bus cuando hay mucha carga
     * no hay necesidad de un servidor
     * cuellos de botella
     * si un nodo no puede retransmitir la red falla
   + malla
     * *totalmente conectada*
     * *parcialmente conectada*
   b.
   + bus: n, cada nodo con el cable central
   + estrella: n-1, cada nodo con el nodo central
   + anillo: n, cada uno con el siguiente y el último con el primero
   + malla: hasta $\frac{n(n-1)}{2}}$, según sea totalmente o parcialmente conectada
2. 
    a. si falla una conexión dos nodos no podrán comunicarse directamente, pero si a dos saltos. los demás se comunican sin problemas
    b. un nodo no puede comunicarse con el central
    c. si falla el bus la red se parte en dos
    d. un fallo en cualquier conexión hace que no pueda haber comunicación
3. la frecuencia más alta es 20KHz, 20000 ciclos por segundo. por el teorema de nyquist el muestreo debe ser de por lo menos 40000 veces por segundo, el doble
4. $C\approx 0.332*B*S/N=0.332*1000*24=7968$, casi 8kbit/s
5. 
    a. bridge o switch. crea dos o más segmentos y si se quiere enviar de un segmento al mismo se corta la comunicación a los demás, alivianando un poco el tráfico
    b. repetidor. sólo se quieren conectar dos dispositivos lejanos
    c. hub. que repita la señal de una red a otra, ya que son pocos dispositivos
    d. bridge o switch. como tienen diferentes estándares, hay que hacer alguna modificación a los datos de capa 1 para que sean entendidos por la otra red
6. 
7. la C está más cerca de A. el mensaje rts llega al ap B y a C pero no a D, que recién activa el nav cuando recibe el cts de B
8. 
   a. subcapa control de acceso al medio
   + iniciación: intercambio de tramas de control para establecer la disponibilidad de las estaciones. terminación: liberación de los recursos. identificación: saber dónde eviar o de dónde viene una trama
   + segmentación y agrupación: dividir o agrupar la información según la longitud de las tramas
   + sincronización octeto caracter: interpretar correctamente los bits. decodificarlos correctamente
   + delimitación de trama: separar las tramas para que sean entendidas por la otra terminal
   b. subcapa control enlace lógico
   + corrección de errores: implementar mecanismos para minimizar los errores que pueden surgir del ruido del medio
   + control de flujo: necesario para no saturar a un receptor con muchos emisores
   + recuperación de fallos: procedimientos para detectar situaciones inusuales como pérdida de tramas, tramas duplicadas o fuera de tiempo
9. DLE-STX-STX-DLE-DLE-ABC-DLE-ETX-DLE-BCD-DLE-STX

   DLE-STX empieza la transmisión

   DLE-DLE-ABC es DLE-ABC porque se usa un escape DLE

   DLE-ETX termina la transmisión

   se transmite STX-DLE-ABC
